#include "H5Composites/H5DType.hxx"

#define H5COMPOSITES_DEFINE_PRED_H5DTYPE(type, pred)                                               \
    H5::PredType H5DType<type>::getType() { return H5::PredType::pred; }

namespace H5Composites {
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(int, NATIVE_INT)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(unsigned int, NATIVE_UINT)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(char, NATIVE_CHAR)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(signed char, NATIVE_SCHAR)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(unsigned char, NATIVE_UCHAR)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(short, NATIVE_SHORT)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(unsigned short, NATIVE_USHORT)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(long, NATIVE_LONG)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(long long, NATIVE_LLONG)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(unsigned long, NATIVE_ULONG)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(unsigned long long, NATIVE_ULLONG)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(float, NATIVE_FLOAT)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(double, NATIVE_DOUBLE)
    H5COMPOSITES_DEFINE_PRED_H5DTYPE(bool, NATIVE_HBOOL)
} // namespace H5Composites